<a href="https://colab.research.google.com/github/Manasa23BEIS123/AIML-12-Week-Program/blob/W1-Manasa/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy pandas

In [ ]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


In [ ]:
# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])

# 2D Array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D Array
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)

print("\n2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)

print("\n3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [ ]:
# Broadcasting example

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

values = np.array([1, 2, 3])

result = arr + values

print("Original array:")
print(arr)

print("\nValues added using broadcasting:")
print(values)

print("\nResult:")
print(result)

Original array:
[[10 20 30]
 [40 50 60]]

Values added using broadcasting:
[1 2 3]

Result:
[[11 22 33]
 [41 52 63]]


In [ ]:
numbers = np.array([1, 2, 3, 4, 5])

squared = numbers ** 2
doubled = numbers * 2
added = numbers + 10

print("Original:", numbers)
print("Squared:", squared)
print("Doubled:", doubled)
print("Added 10:", added)

Original: [1 2 3 4 5]
Squared: [ 1  4  9 16 25]
Doubled: [ 2  4  6  8 10]
Added 10: [11 12 13 14 15]


In [ ]:
matrix_a = np.array([
    [1, 2],
    [3, 4]
])

matrix_b = np.array([
    [5, 6],
    [7, 8]
])

matrix_result = np.matmul(matrix_a, matrix_b)

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nMatrix multiplication result:")
print(matrix_result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix multiplication result:
[[19 22]
 [43 50]]


In [ ]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url)

print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [ ]:
numeric_data = df[
    ["sepal_length", "sepal_width", "petal_length", "petal_width"]
]

mean_values = numeric_data.mean()
std_values = numeric_data.std()

print("Mean:")
print(mean_values)

print("\nStandard Deviation:")
print(std_values)

Mean:
sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

Standard Deviation:
sepal_length    0.828066
sepal_width     0.435866
petal_length    1.765298
petal_width     0.762238
dtype: float64


In [ ]:
correlation_matrix = np.corrcoef(
    numeric_data.to_numpy().T
)

print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


In [ ]:
!git --version


git version 2.34.1


In [ ]:
!git clone https://github.com/Manasa23BEIS123/W1D1-Numpy.git

Cloning into 'W1D1-Numpy'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 2), reused 6 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (10/10), done.
Resolving deltas: 100% (2/2), done.


In [ ]:
%cd W1D1-Numpy
!git log --oneline --all --decorate

/content/W1D1-Numpy
5ce9e2b (HEAD -> feat/aiml-W1-Manasa, origin/main, origin/feat/aiml-W1-Manasa, origin/HEAD) feat: add NumPy fundamentals notebook
9ee74ab feat: add numpy statistics and dataset
a34a8e7 feat: add numpy array operations


In [ ]:
!git branch backup-before-pr

In [ ]:
!git branch

  backup-before-pr
* feat/aiml-W1-Manasa


In [ ]:
!git switch -c main a34a8e7

Switched to a new branch 'main'


In [ ]:
!git push origin main --force

fatal: could not read Username for 'https://github.com': No such device or address


In [ ]:
!git remote -v


origin	https://github.com/Manasa23BEIS123/W1D1-Numpy.git (fetch)
origin	https://github.com/Manasa23BEIS123/W1D1-Numpy.git (push)
